### ISSUE TITLE
In member list, move group name from CSS to HTML

### ISSUE THREAD

**Issue by thewildmage** [coding-camp-wiki/care-package-001#79]
In the member list, the member group of an account is shown via the CSS, e.g.:

```css
.cp-memitem.group5 .mp-hovmg::after {
    content: "Chemical";
}
```

Would be great to move this to the HTML instead so that somebody using this theme would have fewer manual edits to make, since this bit of data is available via Jcink variable.
